global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['basic-web-service.default.svc.cluster.local']
  - job_name: 'kubernetes-pods'
    honor_labels: true
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    # select only those pods that has "prometheus.io/scrape: true" annotation
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
      # set metrics_path (default is /metrics) to the metrics path specified in "prometheus.io/path: <metric path>" annotation.
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
      # set the scrapping port to the port specified in "prometheus.io/port: <port>" annotation and set address accordingly.
    - source_labels: [__address__ __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name